### PR TITLE
Pytest

### PR DESCRIPTION
**Pull request by kevcmk**
Tests are now run by typing: ```py.test``` from the project root.

Diff, tl;dr:
1. Test profiling refactored into pytest plugin, tests/pytest_profile.py (this, along with its parameters, are also shown in ```py.test --help```)
2. Codespeed batch submit working, temporarily disabled because Codespeed fails whenever a branch is uploaded with any name other than "default".
3. Travis YAML updated.  On the test machine, Travis will run with the --cov argument, generating a .coverage report (I'm hoping this will merge seamlessly with the current testing toolchain).

### CODE REVIEW

**Comment by kevcmk** [comment]
@cheelee @travs

**Comment by cheelee** [comment]
Sweet! Thanks @kevcmk I'll take a look once Travis-CI finishes chugging through it.

**Comment by kevcmk** [comment]
Minor fix.

**Comment by cheelee** [comment]
@kevcmk I'll take a bit of time to look at why so many tests fell outside the radar for py.test. In build #494, we had 198 tests, 21 skips, 9 expected fails, 2 unexpected passes.
In the latest PR with build #496, we ended up with only 134 tests, 11 skips, 7 expected fails (?), and 4 unexpected passes (?).

**Comment by travs** [comment]
@kevcmk 
Awesome! Thanks Kevin! 
I'm liking PyTest more and more every time I see what it can do :)

@cheelee 
Good catch. Let's sort out the source of that inconsistency before we merge this one.

**Comment by cheelee** [comment]
Annnd it just occurred to me that after this pull, we'll need to updated our documentation on testing :) Will create a new issue for this.

**Pull request merged**
