### PR TITLE
Uploads synapses from NeuronConnect.xls #87

### PR DESCRIPTION
**Pull request by travs**
URL of the page referenced in #87 is included in the author tag of the `Evidence`, as I couldn't find a single pubmed (or other) article that contains the .xls

### CODE REVIEW

**Comment by mwatts15** [comment]
Slight cleanup that needs to be done: The neuron names that end in numbers less than 10 have leading '0's whereas the ones from the database do not, so there would be duplicates that didn't match up if these were inserted. At this point, we should also verify the counts and consistency checks discussed in the [WormAtlas page](http://www.wormatlas.org/neuronalwiring.html#Connectivitydata) as data integrity tests both for PyOpenWorm and for the spreadsheet itself.

**Comment by travs** [comment]
Absolutely, will be working on a test for consistency as per #88 over the next little while.

**Comment by slarson** [comment]
@aribrich and @ahrasheed just wanted to loop you in on this work as it is a direct result of the pieces you were working on.  #88 could be a direct port of some of the work you've done into this space.

**Comment by slarson** [comment]
@travs thanks for jumping on this!  I agree with @mwatts15 that it would be best to have the test described by #88 before we merge this one, just to be 100% sure that we're not introducing any data errors.  @aribrich and @ahrasheed should be able to help as well as they have some experience with this, so if you want to point to any partial implementations I think we can get a group effort on this.

**Comment by ahrasheed** [comment]
Thank you for notifying. 

[Here](https://github.com/openworm/CElegansNeuroML/blob/master/NeuronConnectFormatted.xlsx) is a cleaned up version of NeuronConnect.xls with the 0s removed. Thanks to @aribrich 

@slarson I was about to open a new issue for the data errors between NeuronConnect and [CElegansNeuronTables](https://github.com/openworm/CElegansNeuroML/blob/master/CElegansNeuronTables.xls) in [c302](https://github.com/openworm/CElegansNeuroML/tree/master/CElegans/pythonScripts/c302). Should that be handled seperately in c302, or will we be eventually using PyOpenWorm in c302 as well ?

**Comment by ahrasheed** [comment]
[Here](https://github.com/openworm/CElegansNeuroML/blob/master/CElegans/pythonScripts/c302/unittests/spreadsheet_comparison_test.py) is a test script that compares NeuronConnect with CElegensNeuronTables, excel file. It has been written in a unittest format, but since there are inconsistencies between the two files, it writes out errors in an excel file instead of simply failing. The comparison logic is very specific to how NeuronConnect maps to CElegensNeuronTables, so I am not sure if it will be very useful in #88. But I can help in writing something similar for #88

**Comment by slarson** [comment]
@ahrasheed awesome.  On the cleaned up version of NeuronConnect.xls, did @aribrich do this manually or did he run a script on it?  For maximum transparency on our methods handling the connectome information, I think it is important that someone can 100% follow the modifications from the original source posted online all the way into the model.  Ideally if it was a script, we could include it in the insert_worm.py.  If it was manual, we'll have to discuss more about this.

As for CElegansNeuronTables -- because of its original uncertain origins, consensus has been forming around the idea of ditching it in favor of NeuronConnect because it is more authoritative. (cc @pgleeson )

And yes, then the plan is to have c302 read from PyOpenWorm, which was actually started in a pull request by @mwatts15 a long time ago: openworm/CElegansNeuroML#12

**Comment by aribrich** [comment]
@slarson, that modification was not done manually. The version that @ahrasheed posted was done in excel, but I have a python script that will do the same thing. I have it working for comparing data in two text files, that I am almost ready to post for comparing excel files as well.

**Comment by slarson** [comment]
@aribrich OK great -- the piece of code then that removes the 0s would be awesome to incorporate in the upload_synapses() method of insert_worm.py.

**Comment by aribrich** [comment]
@slarson I still haven't pushed any of my progress directly into a shared repository, so I'll try to do that in a little bit. In the meantime, I'll just post the python function here - its pretty short:

def formatNames(cols, indexName):
    for i in range(2):
        for char in cols[indexName[i]]:
            if char[-1] != '0':
                char = "".join(char.split("0",1))

Where "Cols" is a python dictionary, and "indexName" is the Key list.

**Comment by aribrich** [comment]
Sorry the indentation didn't hold. Every line is indented one step further.

**Comment by slarson** [comment]
@aribrich thanks!  Fixed the indentation (gotta use three backticks before and after and you get a code block :)

**Comment by slarson** [comment]
The new test is taking too long.  I've submitted a pull request travs/PyOpenWorm#1 to speed it up.  There is another test that needs to be fixed though I think.

**Comment by slarson** [comment]
Boom!  Nice @travs !

**Pull request merged**
