### PR TITLE
Whoa (alpha0.5 history rewrite)

### LINKED ISSUE #99: Remove unnecessary git files to reduce size of repo
When cloning this repo to the local station, the size of the repo is ~100 MB, while the required files (when downloading .zip file) are just ~2 MB.
I guess the problem is with git history files.

### PR DESCRIPTION
**Pull request by travs**
Fixes #99

### CODE REVIEW

**Comment by travs** [comment]
Ok this actually removes some files we need. Going to do a safer rewrite now

**Comment by travs** [comment]
Alright, the files removed were as follows:
```
Deleted files
-------------

	Filename      Git id
	---------------------------------------------------------
	WormData.n3 | b1e582d7 (10.2 MB), cb5032c2 (10.3 MB), ...
	__db.002    | 34d9888d (3.2 MB), b85bbeb9 (3.2 MB), ...
	__db.003    | 72b68568 (62.5 MB), 997b9d1a (58.0 MB), ...
	c^o^s^p^    | 343fcf4c (29.5 MB), f7aade06 (12.7 MB), ...
	c^p^o^s^    | 0d250b42 (29.7 MB), 373460ba (15.3 MB), ...
	c^s^p^o^    | 17e87401 (13.2 MB), a0818aa1 (13.2 MB), ...
	export.trig | 7a5ac377 (10.1 MB)
	export.xml  | fb3cd31e (39.0 MB)
	i2k         | ee6bd6b2 (6.5 MB), 8baf5f39 (2.9 MB), ...
	k2i         | f7e8687b (5.2 MB), 88f64d6d (10.1 MB), ...
	out.n3      | 495fe302 (12.6 MB)
	out.n4      | a4571104 (1.5 MB)
```

This doesn't interfere with the current version of PyOpenWorm alpha0.5

**Comment by slarson** [comment]
Awesome that we've done this.  Looking at the changelog though (84 files changed) -- how do I assure myself that this doesn't change anything when github seems to suggest it changes a lot?! :)  I mean I can always revert it, but any way to reassure myself before I merge?

**Comment by travs** [comment]
Right. The reason this is happening is because all of the commits and blobs now have different SHA-1 tags which are unknown to github. If you look at [my fork](https://github.com/travs/PyOpenWorm) it says "648 commits ahead, 647 commits behind openworm: alpha0.5" (one more because I've made one bugfix commit since).

**Comment by travs** [comment]
@slarson 
Just to close the loop on verifying the history rewrite did not change file contents at the current commit, I cloned both the pre- and post-rewrite versions locally and did a gnu diff:
```
diff -brq \
  --exclude=".git" \
  --exclude=".pyc" \
  PyOpenWorm_post/  PyOpenWorm_pre/
```

The result only showed binary data files (and WormData.n3, which is generated from those files) as differing:
```
Files PyOpenWorm/OpenWormData/WormData.n3 and PyOpenWorm_ow/OpenWormData/WormData.n3 differ
Files PyOpenWorm/OpenWormData/scripts/worm.db and PyOpenWorm_ow/OpenWormData/scripts/worm.db differ
Files PyOpenWorm/OpenWormData/scripts/worm.db.index and PyOpenWorm_ow/OpenWormData/scripts/worm.db.index differ
Files PyOpenWorm/OpenWormData/scripts/worm.db.lock and PyOpenWorm_ow/OpenWormData/scripts/worm.db.lock differ
Files PyOpenWorm/OpenWormData/scripts/worm.db.tmp and PyOpenWorm_ow/OpenWormData/scripts/worm.db.tmp differ
Files PyOpenWorm/dist/PyOpenWorm-0.5.0a0-py2.7.egg and PyOpenWorm_ow/dist/PyOpenWorm-0.5.0a0-py2.7.egg differ
```

Combined with passing tests, it should be it is safe to say that the contents of the repos is functionally identical at this point.

**Pull request merged**
