### PR TITLE
Tests for database integrity

### PR DESCRIPTION
**Pull request by shekhov**
Here a little bit what I think can help to get through the issues openworm#62 and openworm#68

### CODE REVIEW

**Comment by slarson** [comment]
@shekhov this looks great!!  One question: do you think it is possible to instrument db_integrity.py and insert_worm_test.py into test.py, so that rather than printing to the console, we have some assert statements that turn the correct output into an automated test?  This way we don't have to remember what the correct output is supposed to be.

**Comment by shekhov** [comment]
@slarson yes, it is a good idea. Though we still don't know why we ended up with 2 nodes per each neuron. I think that UniqueNeuronNode suppose to be the way it was before this pull - name of the neuron should appear only once in a graph. Once we merge nodes, we can go further with detecting [missing types](https://github.com/openworm/PyOpenWorm/issues/70).

**Comment by slarson** [comment]
@shekhov OK -- I'll merge when you can add those hooks into test.py.  Thanks!

**Comment by shekhov** [comment]
The queries are overweighted now, but at least now we can already run tests. On my old laptop it took about 6 minutes to run. It

**Comment by shekhov** [comment]
@slarson from my point of view, db_integrity.py purpose is more for manual testing the database. And test.py is automatic without using extra sources outside the script. Actually, I was thinking that I still need to do some work on this pull, for example the timing - I will change setUp method to extract all neuron class nodes, and then work only with them. Also, somehow [testNeuronNames](https://github.com/openworm/PyOpenWorm/pull/74/files#diff-b131fe2646b3e4980d06f90692dc2401R73) is still failing, though [testUniqueNeuronsInDB](https://github.com/openworm/PyOpenWorm/pull/74/files#diff-b131fe2646b3e4980d06f90692dc2401R101)  is passing.

**Comment by slarson** [comment]
@shekhov OK the suggestions about setUp sounds good.  Almost there!  Great progress :)

**Comment by slarson** [comment]
Issues have now been closed with another strategy.

**Pull request closed without merging**
