### PR TITLE
Initial work on Python 3 support

### PR DESCRIPTION
**Pull request by jni**
Mostly automated changes using python-modernize. I haven't removed wsgiref from the requirements because maybe it's an upstream dependency? But there is no reference to it other than in the setup.py. Currently I can't install due to libNeuroML, but I'm working on that [also](https://github.com/NeuralEnsemble/libNeuroML/pull/63). =)

### CODE REVIEW

**Comment by jni** [comment]
To help with issue tracking, see also #66 and #270

**Comment by slarson** [comment]
@jni really appreciate the start on this.  We have a much newer code base in progress on the dev branch that we were looking to push into master before too long.  Maybe better to do this work starting from that branch than from master.

Also, let me know if you don't have access to see the build failures on travis-ci -- we'll need to resolve those before any merges.

**Comment by jni** [comment]
@slarson so LibNeuroML master [now](https://github.com/NeuralEnsemble/libNeuroML/pull/64) supports Python 3, which I think was a major roadblock on this... Should I try to rebase on develop or has Py3 support also been added to PyOpenWorm in the meantime? =)

**Comment by mwatts15** [comment]
Thanks for the effort, @jnl. As Stephen said, this can't be merged directly with the latest development. Since it would likely be easier to apply similar automated and manual changes to the dev branch, I'm going to close this PR.

**Pull request closed without merging**
