### PR TITLE
Tally doctests alongside ordinary unit tests.  Fixes #109.  

### LINKED ISSUE #109: Results of doctests should be tallied alongside ordinary unit tests
Currently, test.py runs doctests from README.md.  However, the number of passed and failed tests is not tallied alongside the other unit tests, although they are printed to the terminal.

Maybe we should simply import these tests rather than running the file directly.  

@travs @slarson @mwatts15

### PR DESCRIPTION
**Pull request by gsarma**
With @travs:
1) Created a proper test suite from README doctests
2) The total number of tests does not change, but this is a step towards exposing individual tests with the new breakdown of test.py

### CODE REVIEW

**Comment by gsarma** [comment]
@travs is the problem here that the Readme file contains tests that we are expecting to fail, and now that they are part of the test suite, they are causing the build to fail?

**Comment by slarson** [comment]
Looks like it.  Add an expected failure tag somehow and create a new issue for removing it once they are fixed?

**Comment by gsarma** [comment]
Hmmm. this looks tricky.  You can add a skip or expectedFailure to an individual test, but it's not clear to me how to do that for an entire test suite.

**Comment by gsarma** [comment]
Hmm. this might be tricky to do since the doctests are an entire suite, and the individual tests are not accessible.  Will write back once I've figured it out.  Some relevant reading for anyone interested:
http://stackoverflow.com/questions/12487532/how-do-i-skip-a-whole-python-unittest-module-at-run-time

**Comment by gsarma** [comment]
Interestingly, the way it was done before, we could have simply added @unittest.expectedFailure above the definition for the doctests.

**Comment by slarson** [comment]
Great!

**Pull request merged**
