### PR TITLE
Fix #137 and #128

### LINKED ISSUE #137: Remove duplicate neurons from database
From #128 the doctest was failing, saying that we had 333 neurons instead of the expected 302.

### You can skip this digging and go to my last comment for the results

It turns out that, depending on how we get the neurons form the graph, a different set is returned.

i.e.
```python
>>> len(set(P.Neuron().load()))
333
# but
>>> len(set(P.Worm().neuron_network().neurons()))
302
```

Did some more digging, and the difference between these two sets ends up being:
```python
{u'AS01',
 u'AS02',
 u'AS03',
...
 u'VB09',
 u'VD06'}
```
<sub>[(Full list here)](http://hastebin.com/sixaqumuye.py)</sub>

Neurons that end in a number that begins with zero (ex: "VB**0**9") are duplicated.
Observe:
```python
>>> net = P.Worm().neuron_network()
>>> vb09 = net.aneuron('VB09')
>>> vb9 = net.aneuron('VB9')
# but
>>> vb9 == vb09
False
```

### PR DESCRIPTION
**Pull request by travs**

### CODE REVIEW

**Comment by slarson** [comment]
@travs great progress but not ready for merge yet due to [travis CI fail...](https://travis-ci.org/openworm/PyOpenWorm/builds/66712915)

**Comment by travs** [comment]
@slarson 
This one is [failing now because of the modified names](https://travis-ci.org/openworm/PyOpenWorm/builds/66712915#L605-L606) :(

Working on a fix

**Comment by slarson** [comment]
Yeah I think we chose the wrong one to adapt to.  Looks like as01 instead
of as1 is what we should have chosen :-/

**Comment by slarson** [comment]
Looks good to go!

**Pull request merged**
