### PR TITLE
Dev+issue 90 attempt to merge performance enhancements

### PR DESCRIPTION
**Pull request by slarson**
@mwatts15 says on issue #90 that this may solve some problems but creates new ones.  Creating this pull request so we can see how the tests do & understand what the new problems look like.

### CODE REVIEW

**Comment by slarson** [comment]
Right, so trying to install with these modifications leads to:

'''
Traceback (most recent call last):
  File "insert_worm.py", line 523, in do_insert
    upload_receptors_types_neurotransmitters_neuropeptides_innexins()
  File "insert_worm.py", line 266, in upload_receptors_types_neurotransmitters_neuropeptides_innexins
    e.asserts(r)
  File "/Users/slarson/Documents/pyopenworm-venv/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/simpleProperty.py", line 91, in __call__
    self.set(*args, **kwargs)
  File "/Users/slarson/Documents/pyopenworm-venv/lib/python2.7/site-packages/PyOpenWorm-0.5.3-py2.7.egg/PyOpenWorm/simpleProperty.py", line 148, in set
    str(type(v).__bases__))
Exception: An ObjectProperty only accepts DataObject, SimplePropertyor Variable instances. Got a <class 'PyOpenWorm.dataObject.Neuron_neurotransmitter'> aka (<class 'PyOpenWorm.simpleProperty.DatatypeProperty'>,)
'''

So this is still unfortunately too incomplete to merge at this time.

**Comment by mwatts15** [comment]
Thanks for having a look at my branch. It's, still a work-in-progress, but I thought to share in-case I didn't get a chance to complete. Tests I'm still looking at are below. The doctests, are maybe an hours work. The test_connection_content_matches is up to naming -- the test was incorrect in the first place. I'll have to look more closely at the other 2.
```
tests/DataIntegrityTest.py::DataIntegrityTest::test_connection_content_matches FAILED
tests/DataIntegrityTest.py::DataIntegrityTest::test_correct_connections_number FAILED
tests/DataIntegrityTest.py::DataIntegrityTest::test_correct_number_unique_neurons FAILED
```
and
```
Failed example:
    e.asserts(avdl)
Expected:
    asserts=`AVDL'
Got:
    (Evidence(Evidence:Sulston83), asserts=`AVDL', Neuron(Neuron:AVDL))
...
Failed example:
    e.asserts(avdl.lineageName) # doctest:+ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest README.md[17]>", line 1, in <module>
        e.asserts(avdl.lineageName) # doctest:+ELLIPSIS
      File "./PyOpenWorm/simpleProperty.py", line 90, in __call__
        return _get_or_set(self, *args, **kwargs)
      File "./PyOpenWorm/simpleProperty.py", line 274, in _get_or_set
        return self.set(*args, **kwargs)
      File "./PyOpenWorm/simpleProperty.py", line 132, in set
        str(type(v).__bases__))
    Exception: An ObjectProperty only accepts DataObject, SimpleProperty or Variable instances. Got a <class 'PyOpenWorm.dataObject.Cell_lineageName'> aka (<class 'PyOpenWorm.simpleProperty.DatatypeProperty'>,)

...
File "/media/c90ce379-57e7-4982-931b-dca85b87ca3d/work/openworm/PyOpenWorm2/tests/../README.md", line 148, in README.md
Failed example:
    e.asserts(avdl)
Expected:
    asserts=`AVDL'
Got:
    (Evidence(Evidence:Sulston83), asserts=`AVDL', Neuron(Neuron:AVDL))

...
Failed example:
    avdl.lineageName in list(e0.asserts())
Expected:
    True
Got:
    False
...
Failed example:
    n.neuropeptide("INS-26")
Expected:
    neuropeptide=`INS-26'
Got:
    (Neuron(?V0.185124860881), neuropeptide=`INS-26', INS-26)
```

You'll have to use the latest YAROM dev.

**Comment by mwatts15** [comment]
All right, so now my 5 slowest tests are:
47.87s call     tests/DataIntegrityTest.py::DataIntegrityTest::test_connection_content_matches
12.92s call     tests/DataIntegrityTest.py::DataIntegrityTest::test_correct_connections_number
8.93s call     tests/DataIntegrityTest.py::DataIntegrityTest::test_correct_number_unique_neurons
8.30s call     tests/DataIntegrityTest.py::DataIntegrityTest::test_unconnected_neurons
3.09s call     tests/DataIntegrityTest.py::DataIntegrityTest::test_neurons_have_types

CPU info: http://pastebin.com/qpNB2kwS
Mem info: http://pastebin.com/QdeG2fpq

The remaining test failures are either cosmetic in nature (__repr__ output for doctests) or they existed before this PR. I'll rebase to clean-up the branch history, mark those tests that we're skipped but which would have failed as expected failures, and resubmit with a new PR. If I could get some more timing info like what's given above, I'll add that as part of the docs for the new PR.

**Comment by mwatts15** [comment]
See #278 for the continuation of this thread.

**Pull request closed without merging**
