### PR TITLE
Alpha0.5

### PR DESCRIPTION
**Pull request by mwatts15**
As suggested in #9, I am recommending that alpha0.5 be merged into master. A summary of the changes between alpha0.5 and master is below. Comments, criticisms, and concerns are welcome.

Alpha0.5:

-  provides a declarative syntax for reading and writing properties. Described in the [documentation](http://pyopenworm.readthedocs.org/en/alpha0.5/#pyopenworm).
-  offers an extensible means of defining [new objects](http://pyopenworm.readthedocs.org/en/alpha0.5/making_dataObjects.html) using normal Python classes. New objects and types of objects can be added to shared databases while still being accessible to library versions which lack definition of these additional classes and objects.
-  features [updated documentation](http://pyopenworm.readthedocs.org/en/alpha0.5/making_dataObjects.html) on the changes.
-  enables higher-order statements to be made about the [properties](http://pyopenworm.readthedocs.org/en/alpha0.5/index.html#PyOpenWorm.dataObject.Property) of an object and the relationships between objects.
-  comes with [initial data](https://github.com/mwatts15/OpenWormData) based on pre-existing data sources
-  includes unit tests which cover the core functionality

### CODE REVIEW

**Comment by slarson** [comment]
Looks to me like all that's left is #99 @travs

**Comment by slarson** [comment]
BOOM!  Long road in getting here.  Thanks to @mwatts15 for doing the bulk of the expansion from the original and to @travs for tirelessly pulling us over the finish line!!

**Comment by travs** [comment]
:) Glad this is finally in `master`!

**Comment by gsarma** [comment]
Hooray!

**Pull request merged**
