### PR TITLE
Added tests. Fixes #106 and fixes #103

### LINKED ISSUE #103: Test coverage: net.neurons() not being covered in test set
@gsarma FYI -- this might be something to look into.  Check out issue #102 for the error that should be covered in a test.

### LINKED ISSUE #106: Test coverage: neuropeptide test
We should have a test that verifies that we get "True" out of this.  cc: @gsarma @travs 

Related to issue #105 
```
  >>> n = P.Neuron()
  >>> n.neuropeptide("TH")
  neuropeptide=`TH'

  >>> s = set(x.name() for x in n.load()) 
  >>> s == set(['CEPDR', 'PDER', 'CEPDL', 'PDEL', 'CEPVR', 'CEPVL'])
  True
```

### PR DESCRIPTION
**Pull request by gsarma**

### CODE REVIEW

**Comment by gsarma** [comment]
These tests ran fine for me locally, not sure I understand why the build is failing.  Can someone else comment?

**Comment by travs** [comment]
It seems like the build isn't pulling from the right branch or something. Compare [this line](https://travis-ci.org/openworm/PyOpenWorm#L68) with the [same line from the previous (successful) build](https://travis-ci.org/openworm/PyOpenWorm/builds/63212863#L68).

@slarson Any idea what could be going on here?

Also, the build will fail later, during testing, since the tests we made are not passing yet. Perhaps we should flag them as [expected failures](https://docs.python.org/2/library/unittest.html#unittest.expectedFailure) until the bugs are fixed. We can still see whether or not they passed, but they will not break the build the same way a failure would.

**Comment by gsarma** [comment]
@travs I marked the tests as expected failures- we can remove them once we sort out why the build is failing and the bugs are fixed.

**Comment by slarson** [comment]
@travs @gsarma actually the pulling from a different branch thing is a non issue.  That line is supposed to be different because in the first case it is pulling an actual branch, and in the second case it is creating a branch from a pull request (see [this line](https://travis-ci.org/openworm/PyOpenWorm#L77)).

However, what I am noticing is that the first build grabs [ZODB 4.1.0](https://travis-ci.org/openworm/PyOpenWorm/builds/63212863#L424) whereas the second grabs [ZODB 4.2.0dev](https://travis-ci.org/openworm/PyOpenWorm#L432) and then [tries to grab something called zodbpickle](https://travis-ci.org/openworm/PyOpenWorm#L477) which isn't attempted in the first, and then it falls over trying to build zodbpickle.  Actually that doesn't seem to kill it; it looks like its the final error dealing with [transaction 1.4.4](https://travis-ci.org/openworm/PyOpenWorm#L521) that does it in... but notice it is required by ZODB, and in the first [transaction 1.4.3](https://travis-ci.org/openworm/PyOpenWorm/builds/63212863#L167) is enough.

I think not specifying a version for zodb is letting the latest build pick up a bad version.

Let's try to change [this line](https://github.com/openworm/PyOpenWorm/blob/alpha0.5/requirements.txt#L3) to `zodb==4.1.0` and see if it builds.

**Comment by gsarma** [comment]
@slarson looks like that solved the problem!

**Comment by slarson** [comment]
@gsarma @travs Brilliant!  And that's why we like pull requests :)  Good chance to learn about the code base as we make updates to it for weirdnesses like this!

**Comment by gsarma** [comment]
Indeed!  I didn't actually know what a fork was before this.

**Pull request merged**
